### ISSUE TITLE
Ability to mark devfile stack in registry as deprecated

### ISSUE THREAD

**Issue by kadel** [devfile/api#964] opened 2022-10-06 14:57 UTC
**Which area this feature is related to?**

/area registry

## Which functionality do you think we should add?

We need some way to mark devfiles as deprecated in the devfile registry.
This information should be displayed to the users in the ODC, devfile viewer, odo listing etc... To clearly communicate that it should not be used and that it will get removed in the future.

## Acceptance Criteria

- [ ] Method of setting deprecation for stacks and samples
    - Locally stored and `extraDevfileEntries.yaml` 
- [ ] Create field `deprecated` under index schema

**Comment by thepetk** [comment] 2023-08-11 14:31
Closing as duplicate of https://github.com/devfile/api/issues/1065

**Closed** 2023-08-11 14:31 UTC
Labels: area/registry, severity/blocker
