### ISSUE TITLE
Develop a Devfile Lifecycle management process

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#1066] opened 2023-03-20 15:48 UTC
## Which area this feature is related to?

/area documentation

## Which area is this documentation change is related to?

 /area registry

## Issue details

Currently, we only have onboarding instructions for our registry.  We need to expand on what we have and document what it means to own and maintain a devfile throughout the course of its lifespan

**What mistake did you find / what is missing in the documentation?**

**Comment by kim-tsao** [comment] 2023-03-20 15:54
March 20, 2023:

Discussed details of the deprecation process in today's community call and it was suggested that we set a 1 yr time limit to remove community devfiles whereas, we can leave deprecated devfiles in the product registry indefinitely for now.  We can always adjust the timeframes as needed.

**Comment by kim-tsao** [comment] 2023-10-11 15:12
As discussed in our stand up today, we will not publish this just yet because there are dependent items in the Epic that need to be in place.   We will put this PR in waiting state and create a proposal which will link to this.

**Comment by thepetk** [comment] 2024-01-25 14:42
Bringing this item back in progress and handle the review & merge of the related PR

**Comment by thepetk** [comment] 2024-02-04 09:56
Putting item in progress status as a discussion over the proposed PR will be open

**Comment by thepetk** [comment] 2024-02-12 10:24
The issue is now under review as the proposed PR is ready to get more reviews from the team & the stack owners

**Comment by thepetk** [comment] 2024-02-20 16:27
https://github.com/devfile/registry/pull/208 is now merged. The only detail remains for the documentation is to merge the proposal PR https://github.com/devfile/api/pull/1286 too

cc @kim-tsao

**Comment by thepetk** [comment] 2024-03-07 10:46
cc @kim-tsao 

Closing this issue as the #1286  is now merged

**Closed by thepetk** 2024-03-07 10:46 UTC
Labels: area/registry, devtools-week
