### ISSUE TITLE
Add sample/stack query filter to registry query API

### ISSUE THREAD

**Issue by elsony** [devfile/api#409] opened 2021-04-08 14:22 UTC
This item is a spin-off item from #403.

Given that our current repo does not support sample vs stack definition yet (pending the work for #279), our existing query API only returns a list of stacks. We can provide a temporary implementation to return a static list of samples, e.g. https://github.com/redhat-developer/devfile-sample, for the time being. The list can be a file stored under https://registry.devfile.io/ for the time being.

When we have done #279, we can then modify the implementation to do a life query on the registry. When querying the list of samples, ideally, we should probably combine the list of samples and the list of starters and return all of them as samples.

For the query syntax, this item covers only the sample/stack filtering:
type:sample (the type of resources that needs to match, the initial supported values are sample and stack)

**Comment by GeekArthur** [comment] 2021-05-21 15:21
All the PRs related to this issue are merged, the issue is done.

**Closed by GeekArthur** 2021-05-21 15:21 UTC
Labels: area/registry
