### ISSUE TITLE
Permission issue with java-sprintboot sample

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1628] opened 2024-08-22 23:41 UTC
/kind bug

### Which area is this bug related to?

/area library
/area registry

### Go project

**Operating System and version:** OpenShift 4.16

**Go Pkg Version:** 1.21

## Bug Summary

**Describe the bug:** 

From https://github.com/devfile-samples/devfile-sample-java-springboot-basic/issues/45 by @johnpoth:

> For some reason I'm getting the following error on import:
> ```
> Danger alert:Import is not possible.
> Failed to parse devfile: mkdir docker: permission denied
> ```
> 
> Any suggestions ? Thanks !

**To Reproduce:**

Use OpenShift Developer Console to import [sample git repository](https://github.com/devfile-samples/devfile-sample-java-springboot-basic/tree/main).

This has been identified under OpenShift 4.16 however might not be isolated to this environment.

## Expected behavior

OpenShift Developer Console and any client should be able import and deploy without errors. 

## Any logs, error output, screenshots etc? Provide the devfile that sees this bug, if applicable

![ODC error example](https://private-user-images.githubusercontent.com/7074290/359833314-dd085d08-9e27-4846-b531-cba3556ab846.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNjkwNjAsIm5iZiI6MTcyNDM2ODc2MCwicGF0aCI6Ii83MDc0MjkwLzM1OTgzMzMxNC1kZDA4NWQwOC05ZTI3LTQ4NDYtYjUzMS1jYmEzNTU2YWI4NDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjJUMjMxOTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDg1ODZhM2RmNGExOGFhOTlkNmY1ZjBlYjBjM2MzNDQ0Y2IwNWFmMTY3MDBmZGYzNWY4OTRjNTQ0OTBjOWZjNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FxLvoQ-NlAdv5ULu6IAE-ipFhfsx1LOWrKwpfRekxyY)

## Additional context

It is suspected that this issue can be narrowed down to occur during execution of the `ParseDevfileAndValidate` function, additional investigate is needed to identity the culprit and a solution to resolve this bug.

### Any workaround?

None known at this time.

### Suggestion on how to fix the bug

None known at this time.

**Comment by thepetk** [comment] 2024-08-24 09:15
Sharing some input after a brief investigation I did for this issue. I'm leaning towards two potential reasons for this issue:

1) The issue might occurs once the [ValidateComponents](https://github.com/devfile/api/blob/0c95025d001a3b4b1552d537b4bb493c92f39f7f/pkg/validation/components.go#L42) is called during the execution `ParseDevfileAndValidate`.

2) As this error trace feels let's say "strange" for the functionality of `ParseDevfileAndValidate`, I'd also investigate the possibility of an issue coming from the console side.

**Comment by maysunfaisal** [comment] 2024-08-28 14:00
Per Slack conversation on forum-devconsole at Aug 28, 2024; it seems to be on versions <= 4.16. Version 4.17 didnt have the issue..

**Comment by logonoff** [comment] 2024-08-28 14:03
4.17 might have this issue as well, the difference is just that I was running Dev Console locally, so it was able to create the files without permission issues

**Comment by michael-valdron** [comment] 2024-08-28 14:12
OpenShift Console issue: https://issues.redhat.com/browse/OCPBUGS-39125

**Comment by thepetk** [comment] 2024-08-29 21:09
Sharing here the results of my investigation.

Originally the error trace made me think that the error could be console related. If so I'd expect that the same issue will occur in all the samples (`quarkus`, `python`, `dotnet`, `go` etc). Those samples atm are being imported without an issue.

Apart from that the message is clear that the error occurs during the `parseDevfileAndValidate` and when trying to create the `docker` dir.

Having the above in mind, I've tried to investigate cases the library module needs to create a dir when this specific function is called. I can see that this happens when we're trying to [flatten the parent](https://github.com/devfile/library/blob/c06005c6d45892622fb322048232e1a851b0af58/pkg/devfile/parser/parse.go#L329), upon calling the [parseFromRegistry](https://github.com/devfile/library/blob/c06005c6d45892622fb322048232e1a851b0af58/pkg/devfile/parser/parse.go#L329) which - after a few steps - calls the [PullStackByMediaTypesFromRegistry](https://github.com/devfile/registry-support/blob/3c16242c3a711c30d8f01daf5fc4fbf9442bb7d8/registry-library/library/library.go#L257).

Next, I tried to see if anything changed recently in the parent devfile. We have updated quite recently the parent devfile in order to remove the `odo-devfiles` org from the registry stacks (see [here](https://github.com/devfile/registry/commit/25ef0662410b0cea0d3700beb8fe2a94ce116e89)).

In order to confirm that this is the case I've deployed a registry (minikube + ngrok) with the `java-springboot/1.2.0` (the parent version used by the `java-springboot-sample`) using the old starterproject (e.g. https://github.com/odo-devfiles/springboot-ex). **This fixed the issue and I was able to import the sample**. That said I've opened a [PR](https://github.com/devfile/registry/pull/476) to quickly revert this update so it can fix the error on the console side.

As it's not yet clear (at least to me) why this occurs on the library side (e.g. why a stack cannot use a sample for its starter project), I've opened https://github.com/devfile/api/issues/1633 to investigate further.

Regarding the update of the `starterprojects` fields of the affected stacks (the ones using the `devfile-sample-java-springboot`) I've opened https://github.com/devfile/api/issues/1634.

**Comment by thepetk** [comment] 2024-09-04 19:03
Sharing my latest updates for this issue:

* Based on the error trace we're trying to create a new directory called `docker/`. This happens when we're trying to [flatten the parent stack](https://github.com/openshift/console/blob/master/vendor/github.com/devfile/library/v2/pkg/devfile/parser/parse.go#L71-L75).

* Looking at the latest changes I've noticed we've recently updated the default version of the `java-springboot` stack to `2.2.0`. (see [registry#439](https://github.com/devfile/registry/pull/439)).

* The previous `default` version ([1.2.0](https://github.com/devfile/registry/tree/main/stacks/java-springboot/1.2.0)) has only the `devfile.yaml` as resource. However the new `default` ([2.2.0](https://github.com/devfile/registry/tree/main/stacks/java-springboot/2.2.0)) has additional resources (`docker/`, `kubernetes/`).

* As the [devfile-sample-java-springboot-basic](https://github.com/devfile-samples/devfile-sample-java-springboot-basic/blob/main/devfile.yaml#L17-L20) uses the `id` method to define a parent stack, the parent stack gets flattened through [parseFromRegistry](https://github.com/openshift/console/blob/master/vendor/github.com/devfile/library/v2/pkg/devfile/parser/parse.go#L511).

* Inside the `parseFromRegistry` we're also trying to get the resources of the devfile ([here](https://github.com/openshift/console/blob/master/vendor/github.com/devfile/library/v2/pkg/devfile/parser/parse.go#L527)). Tho we are using a version when we're getting the devfile from registry ([here](https://github.com/openshift/console/blob/master/vendor/github.com/devfile/library/v2/pkg/devfile/parser/parse.go#L517)), for the resources we only use the id.

* As a result we're always downloading the `default` stack's resources when we're trying to flatten parent.

* This should also be an issue on the console side because I think we should be able to create dirs at this point, but we should also fix this on the library side (the issue should occur in [main](https://github.com/devfile/library/blob/main/pkg/devfile/parser/parse.go#L511-L532) too.

## Suggested Fix

- Temporarily revert https://github.com/devfile/registry/pull/439
- Download resources for the given parent stack version when flattening the parent.

## Why the other samples can be imported

Currently no other sample is using a parent that has additional resources. More detailed:
* [devfile-sample-python-basic](https://github.com/devfile-samples/devfile-sample-python-basic/tree/main): Uses [python-2.2.0](https://github.com/devfile/registry/tree/main/stacks/python/2.2.0)
* [devfile-sample-code-with-quarkus](https://github.com/devfile-samples/devfile-sample-code-with-quarkus/tree/main): Uses [java-quarkus/1.4.0](https://github.com/devfile/registry/tree/main/stacks/java-quarkus/1.4.0)
* [devfile-sample-dotnet60-basic](https://github.com/devfile-samples/devfile-sample-dotnet60-basic): No parent.

## How to test the suggested fix

* Start a new cluster
* Update locally your registry's `java-springboot` stack to have as default the `1.3.0` version.
* Deploy on minikube and use ngrok to expose the url.
* Update the sample to use your registry's url.
* Test your sample on openshift.

**Comment by thepetk** [comment] 2024-09-05 14:15
https://github.com/devfile/registry/pull/479 is now merged and I can confirm the issue is fixed (at least on Openshift 4.15)

**Closed by thepetk** 2024-09-05 14:15 UTC
Labels: kind/bug, area/registry, area/library
