### ISSUE TITLE
error 404 - API reference for 2.2.0

### ISSUE THREAD

**Issue by kadel** [devfile/api#710] opened 2021-12-14 13:14 UTC
/area documentation

**Which area this documentation change is related to?**

/area api

## Issue details

**What mistake did you find / what is missing in the documentation?**

Page with API reference for Devfile 2.2.0 returns 404

https://devfile.io/docs/devfile/2.2.0/user-guide/api-reference.html

**Comment by rkratky** [comment] 2022-01-14 09:37
Duplicate of #695

**Closed by rkratky** 2022-01-14 09:37 UTC
Labels: area/documentation, area/api
