### ISSUE TITLE
Devfile registry API doesn't allow cross origin requests.

### ISSUE THREAD

**Issue by rohitkrai03** [devfile/api#719] opened 2022-01-10 15:17 UTC
/kind bug

### Which area this bug is related to?

/area api
/area registry

## What versions of software are you using?

**Operating System:** MacOS

**Go Pkg Version:** N/A

## Bug Summary
**Describe the bug:** Devfile registry API to fetch devfile samples doesn't allow cross origin requests. In order for HAC UI to fetch the devfile samples we need the API to support cross origin requests.

**To Reproduce:** Try to send a GET request to samples registry API. 
 - `fetch('https://registry.devfile.io/index/sample').then((res) => console.log(res))`

## Expected behavior - 
The API should return samples data.

## Any logs, error output, screenshots etc? Provide the devfile that sees this bug, if applicable.

![Screenshot 2022-01-10 at 8 43 34 PM](https://user-images.githubusercontent.com/6041994/148790078-a6824a75-8f4d-4ac5-ade0-5d20c69aef7f.png)

## Additional context

**Any workaround?**

**Suggestion on how to fix the bug**
 - One of the solutions would be for the server to set `Access-Control-Allow-Origin: *` in the response header of the API.

**Comment by johnmcollier** [comment] 2022-01-19 17:02
Fix now live in staging

<img width="1790" alt="Screen Shot 2022-01-19 at 12 01 10 PM" src="https://user-images.githubusercontent.com/6880023/150178698-9b5c6eef-e42f-40e2-b3b4-819ed78f85c5.png">

I will promote the change to production later today.

**Comment by johnmcollier** [comment] 2022-01-19 19:02
@rohitkrai03 The changes are now live in production.

Please verify if the issue is fixed on your end and close this issue out, thanks.

**Closed** 2022-01-20 16:17 UTC
Labels: kind/bug, area/api, area/registry
