### ISSUE TITLE
registry.devfile.io is not usable

### ISSUE THREAD

**Issue by jeffmaury** [devfile/api#965] opened 2022-10-10 15:05 UTC
/kind bug

### Which area this bug is related to?

/area landing-page

## What versions of software are you using?

**Operating System:**
Win10Pro

**Go Pkg Version:**
N/A

## Bug Summary
**Describe the bug:**

When I go to registry.devfile.io, then I can see stacks but after I few seconds, I see:

![image](https://user-images.githubusercontent.com/695993/194897417-e1b08160-89ac-4fd7-b60e-0d44b2830ee4.png)

**To Reproduce:**

## Additional context

**Any workaround?**

**Suggestion on how to fix the bug**

**Comment by elsony** [comment] 2022-10-18 19:57
We tried on two other Win machines and cannot reproduce the problem. Can you provide more information on this issue, e.g. browser, log, etc.? Also, we are in the middle of moving to the redesigned registry viewer. It will be helpful to try out the new viewer when it is available to see if you still see this problem.

**Comment by jeffmaury** [comment] 2022-10-19 06:32
![devfile](https://user-images.githubusercontent.com/695993/196614155-458c053a-8a7c-463e-887f-ba258822abdf.gif)

**Comment by jeffmaury** [comment] 2022-10-19 06:37
I'm running on Firefox / Win11Pro

I can see a lot of errors in the console:

[console-export-2022-10-19_8-35-34.txt](https://github.com/devfile/api/files/9817471/console-export-2022-10-19_8-35-34.txt)

**Comment by jeffmaury** [comment] 2022-10-19 06:39
Having the same error with Microsoft Edge

**Comment by johnmcollier** [comment] 2023-01-27 15:16
@jeffmaury can you retest on Windows when you get the chance?

**Comment by michael-valdron** [comment] 2023-01-27 18:07
New registry viewer change #916 seems to have resolved this issue.

**Closed by michael-valdron** 2023-01-27 18:07 UTC
Labels: kind/bug, area/landing-page
