### ISSUE TITLE
Align devfile titles in registry viewer

### ISSUE THREAD

**Issue by deboer-tim** [devfile/api#611] opened 2021-09-08 16:42 UTC
/kind bug

### Which area this bug is related to?
/area registry

## Bug Summary
**Describe the bug:**
This is minor, but the titles of each devfile should be aligned at the same vertical position. Having them unaligned looks sloppy and is slightly harder to scan.

See screen cap:
<img width="810" alt="align" src="https://user-images.githubusercontent.com/19958075/132541185-dd477c50-22b6-4a40-8679-ad18d1eabcf5.png">

## Expected behavior
Devfile titles are aligned.

## Additional context

**Suggestion on how to fix the bug**
Likely a fixed height/area for the icon so that the label is always at the same vertical position.

**Comment by yangcao77** [comment] 2021-09-14 19:54
two ways to fix the issue:
1. restrict the source icons to be with same size

2. modify css
I'm able to make display name align if remove the max-width limitation for icon image. but the icon size is not guaranteed to be the same. it won't overflow, but some icons may be bigger than others. for instance, vertx:
<img width="948" alt="Screen Shot 2021-09-14 at 3 47 25 PM" src="https://user-images.githubusercontent.com/22285490/133323924-fdd569dd-3d2c-4d97-8c66-c260086f278d.png">

**Comment by schultzp2020** [comment] 2021-09-14 20:00
duplicate of https://github.com/devfile/api/issues/605

**Closed by schultzp2020** 2021-09-14 20:00 UTC
Labels: kind/bug, area/registry
